viewsByHandRuby/config/routes.rb
Rails.application.routes.draw do
  resources :guest_books
  get 'welcome/index'
  get 'welcome/myNewView'
  resources :message
  resources :records
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

viewsByHandRuby/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

viewsByHandRuby/app/models/comment.rb
class Comment < ApplicationRecord
end

viewsByHandRuby/app/models/guest_book.rb
class GuestBook < ApplicationRecord
end

viewsByHandRuby/app/models/message.rb
class Message < ApplicationRecord
end

viewsByHandRuby/app/models/record.rb
class Record < ApplicationRecord
end

viewsByHandRuby/app/models/user.rb
class User < ApplicationRecord
end

viewsByHandRuby/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

viewsByHandRuby/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

viewsByHandRuby/app/controllers/guest_books_controller.rb
class GuestBooksController < ApplicationController
  before_action :set_guest_book, only: %i[ show edit update destroy ]

  # GET /guest_books or /guest_books.json
  def index
    @guest_books = GuestBook.all
  end

  # GET /guest_books/1 or /guest_books/1.json
  def show
  end

  # GET /guest_books/new
  def new
    @guest_book = GuestBook.new
  end

  # GET /guest_books/1/edit
  def edit
  end

  # POST /guest_books or /guest_books.json
  def create
    @guest_book = GuestBook.new(guest_book_params)

    respond_to do |format|
      if @guest_book.save
        format.html { redirect_to guest_book_url(@guest_book), notice: "Guest book was successfully created." }
        format.json { render :show, status: :created, location: @guest_book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @guest_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guest_books/1 or /guest_books/1.json
  def update
    respond_to do |format|
      if @guest_book.update(guest_book_params)
        format.html { redirect_to guest_book_url(@guest_book), notice: "Guest book was successfully updated." }
        format.json { render :show, status: :ok, location: @guest_book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @guest_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guest_books/1 or /guest_books/1.json
  def destroy
    @guest_book.destroy

    respond_to do |format|
      format.html { redirect_to guest_books_url, notice: "Guest book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guest_book
      @guest_book = GuestBook.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def guest_book_params
      params.require(:guest_book).permit(:user, :message)
    end
end

viewsByHandRuby/app/controllers/message_controller.rb
class MessageController < ApplicationController
end

viewsByHandRuby/app/controllers/records_controller.rb
class RecordsController < ApplicationController
    before_action :set_results, only: [:show]
    def index
        @records =Record.first(10)
    end
    def search
    end
    def show
    end
private
    def set_results
        @results = Record.where("artist like ?",params[:q])
    end
end

viewsByHandRuby/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

viewsByHandRuby/app/helpers/application_helper.rb
module ApplicationHelper
end

viewsByHandRuby/app/helpers/comments_helper.rb
module CommentsHelper
end

viewsByHandRuby/app/helpers/guest_books_helper.rb
module GuestBooksHelper
end

viewsByHandRuby/app/helpers/message_helper.rb
module MessageHelper
end

viewsByHandRuby/app/helpers/records_helper.rb
module RecordsHelper
end

viewsByHandRuby/app/helpers/welcome_helper.rb
module WelcomeHelper
end

viewsByHandRuby/app/views/guest_books/_form.html.erb
<%= form_with(model: guest_book) do |form| %>
  <% if guest_book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(guest_book.errors.count, "error") %> prohibited this guest_book from being saved:</h2>

      <ul>
        <% guest_book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user, style: "display: block" %>
    <%= form.text_field :user %>
  </div>

  <div>
    <%= form.label :message, style: "display: block" %>
    <%= form.text_field :message %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

viewsByHandRuby/app/views/guest_books/_guest_book.html.erb
<div id="<%= dom_id guest_book %>">
  <p>
    <strong>User:</strong>
    <%= guest_book.user %>
  </p>

  <p>
    <strong>Message:</strong>
    <%= guest_book.message %>
  </p>

</div>

viewsByHandRuby/app/views/guest_books/edit.html.erb
<h1>Editing guest book</h1>

<%= render "form", guest_book: @guest_book %>

<br>

<div>
  <%= link_to "Show this guest book", @guest_book %> |
  <%= link_to "Back to guest books", guest_books_path %>
</div>

viewsByHandRuby/app/views/guest_books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Guest books</h1>

<div id="guest_books">
  <% @guest_books.each do |guest_book| %>
    <%= render guest_book %>
    <p>
      <%= link_to "Show this guest book", guest_book %>
    </p>
  <% end %>
</div>

<%= link_to "New guest book", new_guest_book_path %>

viewsByHandRuby/app/views/guest_books/new.html.erb
<h1>New guest book</h1>

<%= render "form", guest_book: @guest_book %>

<br>

<div>
  <%= link_to "Back to guest books", guest_books_path %>
</div>

viewsByHandRuby/app/views/guest_books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @guest_book %>

<div>
  <%= link_to "Edit this guest book", edit_guest_book_path(@guest_book) %> |
  <%= link_to "Back to guest books", guest_books_path %>

  <%= button_to "Destroy this guest book", @guest_book, method: :delete %>
</div>

viewsByHandRuby/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ViewsByHand</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

viewsByHandRuby/app/views/message/new.html.erb
<%
@message=Message.new
@message.user="Daniel"
@message.message="Hello from "
@message.save
%>
<h1><%=@message.message%><%=@message.user%></h1>

<%
@message2=Message.new(message:"Hello again from ",user:"Daniel")
@message2.save
%>
<h1><%=@message2.message%><%=@message2.user%></h1>

viewsByHandRuby/app/views/records/new.html.erb
<%
r=Record.new(title:"Spamalot",artist:"Monty Python").save

@myRecord=Record.find(2)
%>
<h1><%=@myRecord.title%> by <%=@myRecord.artist%></h1>
<%
@myRecord=Record.find(2).destroy
%>
<h1><%=@myRecord.title%> by <%=@myRecord.artist%></h1>
<%
r=Random.new
myRecord=Record.find(r.rand(1..4))
%>
<h1><%=myRecord.title%> by <%=myRecord.artist%></h1>

viewsByHandRuby/app/views/records/search.html.erb
<h1>Find Artists</h1>
<%= form_tag("show",method:"get") do %>
<%= label_tag(:q,"Search the top 100") %>
<%= text_field_tag(:q) %>
<%= submit_tag("Search") %>
<% end %>

viewsByHandRuby/app/views/records/select.html.erb
<%= form_tag do %>
<%= collection.select(:titles,:id,Record.all,:id,:title) %>
<p><%= submit_tag('Submit') %></p>
<% end %>
<% if (params.has_key?(:titles)) rec=Record.where("id =?",params[:titles][:id]) %>
<table>
    <tr>
        <tr><th>ID #</th><th>Title</th><th>&nbsp;</th><th>Artist</th></tr>
        <% record.each do |r| %>
    </tr>
    <tr>
        <td><%= r.id %></td><td><%= r.title %></td>
        <td style="padding:0px 15px 0px 25px;">BY</td><td><%= r.artist %></td>
    </tr>
    <% end %>
</table>
<% end %>

viewsByHandRuby/app/views/records/show.html.erb
<table>
    <tr><th>ID #</th><th>Title</th><th>&nbsp;</th><th>Artist</th></tr>
    <% @results.each do |record|%>
    <tr>
        <td><%=record.id%></td><td><%=record.title%></td><td style="padding:0px 15px 0px 25px;">BY</td><td><%=record.artist%></td>
    </tr>
        <% end %>
</table>
<p><%=link_to 'Search Top 100', 'search' %>&nbsp;&nbsp;<%=link_to 'Top 10', 'index' %></p>

viewsByHandRuby/app/views/selections/_states.html.erb
<% 
def us_states
    [
        ['Alabana','AL'],
        ['Alaska','AK']
    ]
end
%>
<%= label_tag(:state,'Select a state:') %>
<%= select_tag :state, options_for_select(us_states) %>

viewsByHandRuby/app/views/selections/index.html.erb
<% Selection Box %>
<%= form_tag() do %>
<%=select_tag :color, options_for_select([['Green',1],['Yellow',2],['Blue',3],['Red',4]])%>
<p><%= render 'states' %></p>
<%end%>

viewsByHandRuby/app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<%= link_to "Welcome", "myNewView" %>

viewsByHandRuby/app/views/welcome/myNewView.html.erb
<h1>My new page</h1>
<%= link_to "Welcome", "index" %>